### ISSUE TITLE
hardhat上 部署bsc测试网络失败，按照视频里面的代码sepolia上可以正常部署成功

### ISSUE THREAD

**Issue by chenghai3219** [smartcontractkit/Web3_tutorial_Chinese#33]
ProviderError: too many arguments, want at most 1
    at HttpProvider.request (E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\hardhat\src\internal\core\providers\http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\@nomicfoundation\hardhat-ethers\src\internal\hardhat-ethers-provider.ts:237:27)
    at E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:235:35
    at async Promise.all (index 0)
    at HardhatEthersSigner._sendUncheckedTransaction (E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:125:18)
    at ContractFactory.deploy (E:\Git\Web3_tutorial_Chinese\lesson-4\node_modules\ethers\src.ts\contract\factory.ts:111:24)
    at main (E:\Git\Web3_tutorial_Chinese\lesson-4\scripts\deployFundMe.js:12:20)

**Comment by QingyangKong** [comment]
请检查你BSC的网络RPC，还有测试币是否有
