### ISSUE TITLE
在第六课跨链中，我编写task测试遇到了这样一个问题，我复制了github源码也同样遇到这个问题，问题出在了最后一个测试的函数中，loadAndSendNFT

### ISSUE THREAD

**Issue by langjiyunmie** [smartcontractkit/Web3_tutorial_Chinese#5]
### 这个是  lock-and-cross.js task测试文件的代码内容\
核心问题就是卡在了这个文件的最后一个函数，下面是一些相关的文件

```const { task } = require("hardhat/config");const { task } = require("hardhat/config");
const { networkConfig } = require("../helper-hardhat-config"); //记录chalink路由一些配置信息

task("lock-and-cross")
  .addOptionalParam("chainSelector", "chain selector of dest chain") **//这里的参数每次都需要用户手动去添加，.addOptionalParam可以让用户选择性去填写参数**
  .addOptionalParam("receiver", "receiver address on dest chain")
  .addParam("tokenid", "token ID to be crossed chain")
  .setAction(async (taskArgs, hre) => {
    let chainSelector;
    let receiver;
    const tokenId = taskArgs.tokenid;
    const firstAccount = (await getNamedAccounts()).firstAccount;

    if (taskArgs.chainSelector) {
      //如果输入了参数，就使用用户输入的
      chainSelector = taskArgs.chainSelector;
    } else {
      //没有输入参数，用默认输入参数
      chainSelector =
        networkConfig[network.config.chainId].CompanionChainSelector; //network会根据我们选择的网络，获取对应的信息
      console.log("chainselector is not set in command");
    }
    console.log(`chainselector is ${chainSelector}`);
    if (taskArgs.receiver) {
      receiver = taskArgs.receiver;
    } else {
      /*  const nftPoolBurnAndMintDeployment = deployments.get("NFTPoolBurnAndMint")  //存在的问题是get方法是在当前源链的环境中，而我们"NFTPoolBurnAndMint"合约是存在于目标链上面的
        receiver = (await nftPoolBurnAndMintDeployment).address */
      const nftPoolBurnAndMintDeployment = await hre.companionNetworks[
        "destchain"
      ].deployments.get("NFTPoolBurnAndMint"); //存在的问题是get方法是在当前源链的环境中，而我们"NFTPoolBurnAndMint"合约是存在于目标链上面的
      receiver = nftPoolBurnAndMintDeployment.address;
      console.log("receiver is not set in command");
    }
    console.log(`receiver is ${receiver}`);

    const linkTokenAddr = networkConfig[network.config.chainId].linkToken;
    const linkToken = await ethers.getContractAt("LinkToken", linkTokenAddr);
    const nftPoolLockAndRelease = await ethers.getContract(
      "NFTPoolLockAndRelease",
      firstAccount
    );
    const transactionTX = await linkToken.transfer(
      nftPoolLockAndRelease.target,
      ethers.parseEther("0")
    );
    await transactionTX.wait(6);
    const balance = await linkToken.balanceOf(nftPoolLockAndRelease.target);
    console.log(`nftPoolLockAndRelease balance:${balance}`);

    const nft = await ethers.getContract("MyToken", firstAccount);
    await nft.approve(nftPoolLockAndRelease.target, tokenId);
    console.log("approve successfully");
    const lockAndSendNFTtx = await nftPoolLockAndRelease.lockAndSendNFT(
      tokenId,
      firstAccount,
      chainSelector,
      receiver
    );
    console.log(
      `ccip transaction is sent, the tx hash is ${lockAndSendNFTtx.hash}`
    );
  });

module.exports = {};
```

helper-hardhat-config配置文件内容
```
developmentChains = ["local", "hardhat"];
const networkConfig = {
  11155420: {
    name: "op_sepolia",
    router: "0x114A20A10b43D4115e5aeef7345a1A71d2a60C57",
    linkToken: "0xE4aB69C077896252FAFBD49EFD26B5D171A32410",
    CompanionChainSelector:"5224473277236331295"
  },
  80002: {
    name: "amoy",
    router: "0x9C32fCB86BF0f4a1A8921a9Fe46de3198bb884B2",
    linkToken: "0x0Fd9e8d3aF1aaee056EB9e802c3A762a667b1904",
    CompanionChainSelector:"16281711391670634445",
  },
};
module.exports = {
  developmentChains,
  networkConfig,
};
```

### hardhat-config配置文件内容
```
require("@nomicfoundation/hardhat-toolbox");
require("@nomicfoundation/hardhat-ethers");
require("hardhat-deploy");
require("hardhat-deploy-ethers");
require("@nomicfoundation/hardhat-chai-matchers");
require("@chainlink/env-enc").config();
require("./task");

const PRIVATE_KEY = process.env.PRIVATE_KEY;
const SEPOLIA_RPC_URL = process.env.SEPOLIA_RPC_URL;
const AMOY_RPC_URL = process.env.AMOY_RPC_URL;
const OP_SEPOLIA_RPC_URL = process.env.OP_SEPOLIA_RPC_URL;

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity:{
    compilers: [
      {
        version: "0.8.20"
      },
      {
        version: "0.8.19"
      }
    ]
  },
  namedAccounts: {
    firstAccount: {
      default: 0,
    },
  },

 networks: {
  sepolia: {
    url: SEPOLIA_RPC_URL,
    accounts: [PRIVATE_KEY],
    chainId: 111555111,
    blockConfirmations: 6,
    gas: 3000000, // 设置 Gas 限制
    gasPrice: 20000000000, // 设置 Gas 价格为 20 Gwei
  },
  amoy: {
    url: AMOY_RPC_URL,
    accounts: [PRIVATE_KEY],
    chainId: 80002,
    blockConfirmations: 6,
    gas: 3000000,
    gasPrice: 20000000000,
    companionNetworks: {
      destchain: "op_sepolia",
    },
  },
  op_sepolia: {
    url: OP_SEPOLIA_RPC_URL,
    accounts: [PRIVATE_KEY],
    chainId: 11155420,
    blockConfirmations: 6,
    gas: 3000000,
    gasPrice: 20000000000,
    companionNetworks: {
      destchain: "amoy",
    },
  },
},
};

```

### 在进行此命令之前，是进行过test测试的，test测试内容如下：

```const { expect } = require("chai");
const { getNamedAccounts, deployments, ethers } = require("hardhat");

//定义前提变量，可以写在 before模块里面
//变量：合约地址，测试账户
//let声明变量，before模块外的可以使用这些变量，不等于是全局变量，在模块外也是保留原来的生命
let firstAccount;
let ccipSimulator;
let nft;
let nftPoolLockAndRelease;
let wnft;
let NFTPoolBurnAndMint;
let chainSelector;

before(async function () {
  firstAccount = (await getNamedAccounts()).firstAccount; //getNamedAccounts() 返回的是一组地址
  await deployments.fixture(["all"]); //重新部署全部的合约
  ccipSimulator = await ethers.getContract("CCIPLocalSimulator", firstAccount);
  nft = await ethers.getContract("MyToken", firstAccount);
  nftPoolLockAndRelease = await ethers.getContract(
    "NFTPoolLockAndRelease",
    firstAccount
  );
  wnft = await ethers.getContract("WrappedMytoken", firstAccount);
  NFTPoolBurnAndMint = await ethers.getContract(
    "NFTPoolBurnAndMint",
    firstAccount
  );
  const config = await ccipSimulator.configuration();
  chainSelector = config.chainSelector_;
});
//sourcechain -> destchain
describe("sourcechain -> destchain", async function () {
  it("是否可以成功铸造nft", async function () {
    const signer = await ethers.getSigner(firstAccount);
    await nft.connect(signer).safeMint(firstAccount);
    const owner = await nft.ownerOf(0);
    expect(owner).to.equal(firstAccount);
  });

  it("是否可以在源链锁定nft", async function () {
    await nft.approve(nftPoolLockAndRelease.target, 0);
    await ccipSimulator.requestLinkFromFaucet(
      nftPoolLockAndRelease,
      ethers.parseEther("10")
    );
    await nftPoolLockAndRelease.lockAndSendNFT(
      0,
      firstAccount,
      chainSelector,
      NFTPoolBurnAndMint.target
    );
    const owner = await nft.ownerOf(0);
    expect(owner).to.equal(nftPoolLockAndRelease);
  });

  it("消息是否可以被ccip成功发送并在在目标链得到了wrapped_nft", async function () {
    const owner = await wnft.ownerOf(0);
    expect(owner).to.equal(firstAccount);
  });
});

describe("destchain -> sourcechain", async function () {
  it("是否可以烧掉nft", async function () {
    await wnft.approve(NFTPoolBurnAndMint.target, 0);
    await ccipSimulator.requestLinkFromFaucet(
      NFTPoolBurnAndMint,
      ethers.parseEther("10")
    );
    await NFTPoolBurnAndMint.BurnAndSendNFT(
      0,
      firstAccount,
      chainSelector,
      nftPoolLockAndRelease.target
    );
    const totalSupply = await wnft.totalSupply();
    expect(totalSupply).to.equal(0);
  });

  it("并可以消息从目标链发送到源链,是否可以在源链上解锁nft",async function () {
    const owner = await nft.ownerOf(0)
    expect(owner).to.equal(firstAccount)
  })
});
```

该文件成功执行，说明合约文件是没有问题的。

### 下面是我的流程
我使用的是 op_sepolia  和  Amoy 测试网。
使用的hardhat执行命令为
`npx hardhat lock-and-cross --tokenid 0 --network op_sepolia`

以下是报错信息
```chainselector is not set in command
chainselector is 5224473277236331295
receiver is not set in command
receiver is 0x66CCd91D7153727576AfF1Fce7929De2B74d8dfE
nftPoolLockAndRelease balance:20000000000000000000
approve successfully
An unexpected error occurred:

ProviderError: execution reverted
    at HttpProvider.request (/home/langji/chainlink_learning/kualian_chainlink/node_modules/hardhat/src/internal/core/providers/http.ts:107:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (/home/langji/chainlink_learning/kualian_chainlink/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:246:27)
    at /home/langji/chainlink_learning/kualian_chainlink/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 0)
    at HardhatEthersSigner._sendUncheckedTransaction (/home/langji/chainlink_learning/kualian_chainlink/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (/home/langji/chainlink_learning/kualian_chainlink/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at send (/home/langji/chainlink_learning/kualian_chainlink/node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at Proxy.lockAndSendNFT (/home/langji/chainlink_learning/kualian_chainlink/node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at SimpleTaskDefinition.action (/home/langji/chainlink_learning/kualian_chainlink/task/lock-and-cross.js:54:30)
```
可以看出就是卡在了lockAndSendNFT。但是影响此操作的就是授权问题，依据回显结果，说明是成功进行了授权的。且有充足的linktoken进行操作。之前尝试了，但是没有解决。大佬求助

**Comment by QingyangKong** [comment]
感谢反馈，我正在查看这个问题

**Comment by wzl521** [comment]
请问这个问题解决了吗？我也遇到了相同的问题

**Comment by langjiyunmie** [comment]
可以把文件的啥内容一起发出来，等待大佬解决

**Comment by wzl521** [comment]
> 可以把文件的啥内容一起发出来，等待大佬解决

内容一样，也就配置文件不一样，require("@chainlink/env-enc").config()
require("@nomicfoundation/hardhat-toolbox");
require("@nomicfoundation/hardhat-ethers");
require("hardhat-deploy");
require("hardhat-deploy-ethers");
require("./task")

const PRIVATE_KEY = process.env.PRIVATE_KEY
const SEPOLIA_RPC_URL = process.env.SEPOLIA_RPC_URL
const LINEA_SEPOLIA_RPC_URL = process.env.LINEA_SEPOLIA_RPC_URL

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: {
    compilers: [
      {
        version: "0.8.27"
      }
    ]
  },
  namedAccounts: {
    firstAccount: {
      default: 0
    }
  },
  networks: {
    sepolia: {
      url: SEPOLIA_RPC_URL,
      accounts: [PRIVATE_KEY],
      chainId: 11155111,
      blockConfirmations: 6,
      companionNetworks: {
        destChain: "linea"
      }
    },
    linea: {
      url: LINEA_SEPOLIA_RPC_URL,
      accounts: [PRIVATE_KEY],
      chainId: 59141,
      blockConfirmations: 6,
      companionNetworks: {
        destChain: "sepolia"
      }
    }
  }
};developmentChains = ["hardhat", "localhost"]
const networkConfig = {
    11155111: {
        name: "sepolia",
        router: "0x0BF3dE8c5D3e8A2B34D2BEeB17ABfCeBaf363A59",
        linkToken: "0x779877A7B0D9E8603169DdbD7836e478b4624789",
        companionChainSelector: "5719461335882077547" // destchain
    },
    59141: {
        name: "linea",
        router: "0xB4431A6c63F72916151fEA2864DBB13b8ce80E8a",
        linkToken: "0xF64E6E064a71B45514691D397ad4204972cD6508",
        companionChainSelector: "16015286601757825753" // destchain
    }

}
module.exports = {
    developmentChains,
    networkConfig
}

**Comment by QingyangKong** [comment]
@langjiyunmie , 我在使用repo中的代码进行 Ethereum Sepolia 到 Polygon Amoy 的时候没有遇到这个问题。我看你的 helper 文件，companion network 的 chainselector 写反了，似乎是这个问题引起的。
作为sourcechain，companion network 应该是 destination chain 而非本身的 chainselector，你把helper-hardhat-config 文件中，11155420 和 80002 的 companionChainSelector 互换一下，应该就好了。另外 companionChainSelector 第一个字母是小写。

**Comment by QingyangKong** [comment]
> > 可以把文件的啥内容一起发出来，等待大佬解决
> 
> 内容一样，也就配置文件不一样，require("@chainlink/env-enc").config() require("@nomicfoundation/hardhat-toolbox"); require("@nomicfoundation/hardhat-ethers"); require("hardhat-deploy"); require("hardhat-deploy-ethers"); require("./task")
> 
> const PRIVATE_KEY = process.env.PRIVATE_KEY const SEPOLIA_RPC_URL = process.env.SEPOLIA_RPC_URL const LINEA_SEPOLIA_RPC_URL = process.env.LINEA_SEPOLIA_RPC_URL
> 
> /** @type import('hardhat/config').HardhatUserConfig */ module.exports = { solidity: { compilers: [ { version: "0.8.27" } ] }, namedAccounts: { firstAccount: { default: 0 } }, networks: { sepolia: { url: SEPOLIA_RPC_URL, accounts: [PRIVATE_KEY], chainId: 11155111, blockConfirmations: 6, companionNetworks: { destChain: "linea" } }, linea: { url: LINEA_SEPOLIA_RPC_URL, accounts: [PRIVATE_KEY], chainId: 59141, blockConfirmations: 6, companionNetworks: { destChain: "sepolia" } } } };developmentChains = ["hardhat", "localhost"] const networkConfig = { 11155111: { name: "sepolia", router: "0x0BF3dE8c5D3e8A2B34D2BEeB17ABfCeBaf363A59", linkToken: "0x779877A7B0D9E8603169DdbD7836e478b4624789", companionChainSelector: "5719461335882077547" // destchain }, 59141: { name: "linea", router: "0xB4431A6c63F72916151fEA2864DBB13b8ce80E8a", linkToken: "0xF64E6E064a71B45514691D397ad4204972cD6508", companionChainSelector: "16015286601757825753" // destchain }
> 
> } module.exports = { developmentChains, networkConfig }

如果授权能成功说明脚本可以成功获取到你之前部署的所有的合约，但是如果授权成功，并且合约中也有balance，最后无法跨链成功，一般是因为在调用 CCIP 跨链的时候参数配置不正确。我建议可以先尝试使用 repo 中的代码进行 eth sepolia 到 Amoy 的跨链看看是否成功，排除参数错误的问题，然后再逐步修改已有的代码。

**Comment by langjiyunmie** [comment]
> [@langjiyunmie](https://github.com/langjiyunmie) , 我在使用repo中的代码进行 Ethereum Sepolia 到 Polygon Amoy 的时候没有遇到这个问题。我看你的 helper 文件，companion network 的 chainselector 写反了，似乎是这个问题引起的。 作为sourcechain，companion network 应该是 destination chain 而非本身的 chainselector，你把helper-hardhat-config 文件中，11155420 和 80002 的 companionChainSelector 互换一下，应该就好了。另外 companionChainSelector 第一个字母是小写。

感谢，我之后再次进行了复现解决了。

**Comment by chenchen53698** [comment]
感谢 我的也是配置文件的问题  我使用的是17000 holesky 换成80002就可以了

**Comment by Don5211314** [comment]
> 感谢 我的也是配置文件的问题 我使用的是17000 holesky 换成80002就可以了

请问是17000不能进行跨链吗？？只能用80002 amoy吗
